
version: '3'

services:
  app1:
    build: ./app1
    container_name: app1
    ports:
      - "8001:8001"
  
  app2:
    build: ./app2
    container_name: app2
    ports:
      - "8002:8002"
  
  app3:
    build: ./app3
    container_name: app3
    ports:
      - "8003:8003"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
